theme: jekyll-theme-cayman
title: Welcome to My Journey into the Digital World!
description: Welocme Aboard!! <br> I am Nibedita. Welcome to my personal github website. <br> My Moto of Life is <br> Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world. <br> ~Albert Einstein
plugins: 
- jekyll-remote-theme
show_downloads: True
