theme: jekyll-theme-cayman
title: "Welcome to Nibedita's Journey to the Digital World!"
description: My Moto of Life: <br> Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world. <br> ~Albert Einstein
plugins: 
- jekyll-remote-theme
show_downloads: True
