theme: jekyll-theme-cayman
title: Nibedita Chakraborty
description: B.Tech. Computer Science | 2020-2024 | MSIT, MAKAUT, Kolkata <br> Dual B.S. degree in Data Science and Programming | October 2020 onwards | IIT, Madras
plugins: 
- jekyll-remote-theme
show_downloads: True
